Dv 140 fe front connect back
TeamRichardStallman/dv-front pull request #26
Opened 2024-11-08 07:56 UTC by andbeyond0331

## 🌎 PR 요약

🌱 작업한 브랜치

- Dv 140 fe front connect back

💬 관련 이슈

- 이슈넘버

## 📚 작업한 내용

- 회원가입
- 로그인
- setup

## 📍 참고 사항

- .env에 
NEXT_PUBLIC_BACK_URL 이거 추가해야 돌아감

## 📝 리뷰 중점 사안(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

2024-11-08 13:48 UTC, LEE-DA-EUN approved these changes
확인했습니다!

2024-11-08 14:44 UTC, Danny-Jo requested changes
테스트해보니 몇 가지 문제가 있어서 수정이 필요해보입니다.

일단 테스트 전에 
`NEXT_PUBLIC_BACK_URL=http://dev-api.devterview.com:8080`
를 환경변수에 추가하고 시작했습니다.
이외에 추가로 설정해줘야 하는 것이 있으면 말씀해주세요


1. 면접 정보 입력 확인 페이지에서 다음 버튼을 눌러 넘어갈 때 에러 발생
아래 스크린샷에 에러와 관련된 메시지가 떠있습니다.
dataToSend 데이터가 완전히 채워져있지 않고 cors 문제가 발생한 것으로 보입니다. 
백엔드 개발서버에서 cors설정으로 3000port를 열어주셔야 합니다. (ex. localhost:3000)

### 스크린샷
<img width="1910" alt="스크린샷 2024-11-08 오후 11 29 27" src="https://github.com/user-attachments/assets/65c9f2fd-cce1-43c4-84e5-2cf596bae214">
<img width="1100" alt="스크린샷 2024-11-08 오후 11 32 16" src="https://github.com/user-attachments/assets/e466db20-323f-4f32-8c06-143cf005cf18">


2. oauth 로그인을 해도 로그인 여부를 알 수 없습니다.
oauth 로그인에 성공하면 localhost:3000으로 돌아오는게 아니라 dev.devterview.com 으로 이동합니다. 더 큰 문제는 accessToken이 cookie에도, localStorage에도 저장되지 않습니다. 즉 인증정보가 없어 로그인 여부를 확인할 수 없습니다.

<img width="1916" alt="스크린샷 2024-11-08 오후 11 37 17" src="https://github.com/user-attachments/assets/71d601b3-1651-4ece-a410-41f5e6ba35e8">
<img width="1916" alt="스크린샷 2024-11-08 오후 11 37 30" src="https://github.com/user-attachments/assets/44065ca0-37ce-41c1-9ff9-9a7f530d4160">

2024-11-08 14:47 UTC, andbeyond0331 commented
> 테스트해보니 몇 가지 문제가 있어서 수정이 필요해보입니다.
> 
> 일단 테스트 전에 `NEXT_PUBLIC_BACK_URL=http://dev-api.devterview.com:8080` 를 환경변수에 추가하고 시작했습니다. 이외에 추가로 설정해줘야 하는 것이 있으면 말씀해주세요
> 
> 1. 면접 정보 입력 확인 페이지에서 다음 버튼을 눌러 넘어갈 때 에러 발생
>    아래 스크린샷에 에러와 관련된 메시지가 떠있습니다.
>    dataToSend 데이터가 완전히 채워져있지 않고 cors 문제가 발생한 것으로 보입니다.
>    백엔드 개발서버에서 cors설정으로 3000port를 열어주셔야 합니다. (ex. localhost:3000)
> 
> ### 스크린샷
> <img alt="스크린샷 2024-11-08 오후 11 29 27" width="1910" src="https://private-user-images.githubusercontent.com/173679024/384408360-65c9f2fd-cce1-43c4-84e5-2cf596bae214.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzc1MjQsIm5iZiI6MTczMTA3NzIyNCwicGF0aCI6Ii8xNzM2NzkwMjQvMzg0NDA4MzYwLTY1YzlmMmZkLWNjZTEtNDNjNC04NGU1LTJjZjU5NmJhZTIxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNDQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTIxNzgxZWE3NmRmZTE4M2VmMmM1N2JhYzMwNDY4NGU5M2VmZThmZDU2Yzg2MWFmZGIyOWRmNzkzNzg3NWViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0Xp4N1ES88MjAntIobpcdPCQU9i5DsHgNYwggfxOMYQ"> <img alt="스크린샷 2024-11-08 오후 11 32 16" width="1100" src="https://private-user-images.githubusercontent.com/173679024/384408436-e466db20-323f-4f32-8c06-143cf005cf18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzc1MjQsIm5iZiI6MTczMTA3NzIyNCwicGF0aCI6Ii8xNzM2NzkwMjQvMzg0NDA4NDM2LWU0NjZkYjIwLTMyM2YtNGYzMi04YzA2LTE0M2NmMDA1Y2YxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNDQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzgxYTA5MDhkMjQ4NjYyYWVhNGNjOWZjNTA1ZDRmOTEwM2Y1MDM2NTQ5OTMyMTc1MWRiY2EwYWQ4YzhiYmMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PMHVQheQ158gflpDbU6IBVFzF8OnjdVdB14ncvr93kE">
> 2. oauth 로그인을 해도 로그인 여부를 알 수 없습니다.
>    oauth 로그인에 성공하면 localhost:3000으로 돌아오는게 아니라 dev.devterview.com 으로 이동합니다. 더 큰 문제는 accessToken이 cookie에도, localStorage에도 저장되지 않습니다. 즉 인증정보가 없어 로그인 여부를 확인할 수 없습니다.
> 
> <img alt="스크린샷 2024-11-08 오후 11 37 17" width="1916" src="https://private-user-images.githubusercontent.com/173679024/384409831-71d601b3-1651-4ece-a410-41f5e6ba35e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzc1MjQsIm5iZiI6MTczMTA3NzIyNCwicGF0aCI6Ii8xNzM2NzkwMjQvMzg0NDA5ODMxLTcxZDYwMWIzLTE2NTEtNGVjZS1hNDEwLTQxZjVlNmJhMzVlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNDQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNmJlMjk5MTVmZGRlOTQ1OTk5YmM2Y2VkMzBjNjg3MGY1ZTU2MGZkYmUxZTFhMTY0YzFiMjFkNjU5NDlkYjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KSYzvAb5563Cls9uulK73u4c54i-r-bWz3wGBNIHktU"> <img alt="스크린샷 2024-11-08 오후 11 37 30" width="1916" src="https://private-user-images.githubusercontent.com/173679024/384409901-44065ca0-37ce-41c1-9ff9-9a7f530d4160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzc1MjQsIm5iZiI6MTczMTA3NzIyNCwicGF0aCI6Ii8xNzM2NzkwMjQvMzg0NDA5OTAxLTQ0MDY1Y2EwLTM3Y2UtNDFjMS05ZmY5LTlhN2Y1MzBkNDE2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNDQ3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGFhM2Y5MTY3NzYyOWIyOGRlMDU5NmYxN2UxMzk1MDYyOTY3Nzc5ZDY2NDhjN2MyNGE2NzYwOTE2OWJiYzk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3Vv2j4VOp9wgrCcaS6OEHSEnNFiD1SQTR91lAMq-sEU">

혹시 .env 어떻게 설정하셨는지 공유 가능한가요?

2024-11-11 01:12 UTC, andbeyond0331 commented
> 테스트해보니 몇 가지 문제가 있어서 수정이 필요해보입니다.
> 
> 일단 테스트 전에 `NEXT_PUBLIC_BACK_URL=http://dev-api.devterview.com:8080` 를 환경변수에 추가하고 시작했습니다. 이외에 추가로 설정해줘야 하는 것이 있으면 말씀해주세요
> 
> 1. 면접 정보 입력 확인 페이지에서 다음 버튼을 눌러 넘어갈 때 에러 발생
>    아래 스크린샷에 에러와 관련된 메시지가 떠있습니다.
>    dataToSend 데이터가 완전히 채워져있지 않고 cors 문제가 발생한 것으로 보입니다.
>    백엔드 개발서버에서 cors설정으로 3000port를 열어주셔야 합니다. (ex. localhost:3000)
> 
> ### 스크린샷
> <img alt="스크린샷 2024-11-08 오후 11 29 27" width="1910" src="https://private-user-images.githubusercontent.com/173679024/384408360-65c9f2fd-cce1-43c4-84e5-2cf596bae214.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyODc3ODAsIm5iZiI6MTczMTI4NzQ4MCwicGF0aCI6Ii8xNzM2NzkwMjQvMzg0NDA4MzYwLTY1YzlmMmZkLWNjZTEtNDNjNC04NGU1LTJjZjU5NmJhZTIxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwMTExMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmQ3YjIyYTU1YjlmMmVjYTlmMDA1NjJlN2NmNTIxZDA3OWRkMGM2M2E1ZjZkNWM5ODlhOTY4YTAxMGQ2YzllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UDpFTLjXtuqaMN4zxAzupTG2wC-whP6LZZpU7i1r0Lc"> <img alt="스크린샷 2024-11-08 오후 11 32 16" width="1100" src="https://private-user-images.githubusercontent.com/173679024/384408436-e466db20-323f-4f32-8c06-143cf005cf18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyODc3ODAsIm5iZiI6MTczMTI4NzQ4MCwicGF0aCI6Ii8xNzM2NzkwMjQvMzg0NDA4NDM2LWU0NjZkYjIwLTMyM2YtNGYzMi04YzA2LTE0M2NmMDA1Y2YxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwMTExMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDlmZDk1NmY3MWExYzdmMDYyN2IzY2EyMjA2MGQ1YWJlNzY3NDdlMzk5YWE0OTczOTlhNzhhNWYzMDUwYTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hxh5dKbNpPUev3olcPzGuN72_cZWU2PfF5m9qeVf6fo">
> 2. oauth 로그인을 해도 로그인 여부를 알 수 없습니다.
>    oauth 로그인에 성공하면 localhost:3000으로 돌아오는게 아니라 dev.devterview.com 으로 이동합니다. 더 큰 문제는 accessToken이 cookie에도, localStorage에도 저장되지 않습니다. 즉 인증정보가 없어 로그인 여부를 확인할 수 없습니다.
> 
> <img alt="스크린샷 2024-11-08 오후 11 37 17" width="1916" src="https://private-user-images.githubusercontent.com/173679024/384409831-71d601b3-1651-4ece-a410-41f5e6ba35e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyODc3ODAsIm5iZiI6MTczMTI4NzQ4MCwicGF0aCI6Ii8xNzM2NzkwMjQvMzg0NDA5ODMxLTcxZDYwMWIzLTE2NTEtNGVjZS1hNDEwLTQxZjVlNmJhMzVlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwMTExMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjczNjk2YmJkNTJiZjhiNjJhNjg3NjJkZDRkODQyZGUyYjMzNDc5MTI3Mjg3ZWEzYTIyNTBlYWNhZDZkNTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2qDrbdd0bIEBA7jkvtctMsgVHSdkCzsUknYPP6RQpZ4"> <img alt="스크린샷 2024-11-08 오후 11 37 30" width="1916" src="https://private-user-images.githubusercontent.com/173679024/384409901-44065ca0-37ce-41c1-9ff9-9a7f530d4160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyODc3ODAsIm5iZiI6MTczMTI4NzQ4MCwicGF0aCI6Ii8xNzM2NzkwMjQvMzg0NDA5OTAxLTQ0MDY1Y2EwLTM3Y2UtNDFjMS05ZmY5LTlhN2Y1MzBkNDE2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMVQwMTExMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWRjZTBkOTUzZWI3NWNkYmVjMTk5MDA5MThiNjJkMTAzNzBmZjNkYjMxN2QwYzljNGFlMmUzZjYxMjhiZTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fpGRajHtXBuq-wiV_dP1A8m8u5aZtyX-2S-5D1qEMdg">

확인해보니 dev 환경에서는 로컬 cross origin 처리를 하지 않아 생기는 문제입니다. local 에서 백 실행시켜서 돌려보면 잘 돌아갑니다.

2024-11-11 08:46 UTC, Danny-Jo approved these changes

2024-11-11 10:01 UTC, merged